config/routes.rb
MusicApp::Application.routes.draw do
  resources :gigs

end

app/models/gig.rb
class Gig < ActiveRecord::Base
  attr_accessible :date, :name, :time, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  # GET /gigs
  # GET /gigs.json
  def index
    @gigs = Gig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gigs }
    end
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
    @gig = Gig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gig }
    end
  end

  # GET /gigs/new
  # GET /gigs/new.json
  def new
    @gig = Gig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gig }
    end
  end

  # GET /gigs/1/edit
  def edit
    @gig = Gig.find(params[:id])
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(params[:gig])

    respond_to do |format|
      if @gig.save
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render json: @gig, status: :created, location: @gig }
      else
        format.html { render action: "new" }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gigs/1
  # PUT /gigs/1.json
  def update
    @gig = Gig.find(params[:id])

    respond_to do |format|
      if @gig.update_attributes(params[:gig])
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig = Gig.find(params[:id])
    @gig.destroy

    respond_to do |format|
      format.html { redirect_to gigs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/gigs/_form.html.erb
<%= form_for(@gig) do |f| %>
  <% if @gig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gig.errors.count, "error") %> prohibited this gig from being saved:</h2>

      <ul>
      <% @gig.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gigs/edit.html.erb
<h1>Editing gig</h1>

<%= render 'form' %>

<%= link_to 'Show', @gig %> |
<%= link_to 'Back', gigs_path %>

app/views/gigs/index.html.erb
<h1>Listing gigs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Time</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gigs.each do |gig| %>
  <tr>
    <td><%= gig.name %></td>
    <td><%= gig.date %></td>
    <td><%= gig.time %></td>
    <td><%= gig.url %></td>
    <td><%= link_to 'Show', gig %></td>
    <td><%= link_to 'Edit', edit_gig_path(gig) %></td>
    <td><%= link_to 'Destroy', gig, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gig', new_gig_path %>

app/views/gigs/new.html.erb
<h1>New gig</h1>

<%= render 'form' %>

<%= link_to 'Back', gigs_path %>

app/views/gigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gig.name %>
</p>

<p>
  <b>Date:</b>
  <%= @gig.date %>
</p>

<p>
  <b>Time:</b>
  <%= @gig.time %>
</p>

<p>
  <b>Url:</b>
  <%= @gig.url %>
</p>


<%= link_to 'Edit', edit_gig_path(@gig) %> |
<%= link_to 'Back', gigs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>